-- MySQL Script generated by MySQL Workbench
-- Tue Nov 13 18:50:24 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MyFirstDB
-- -----------------------------------------------------
-- Testing DB

-- -----------------------------------------------------
-- Schema MyFirstDB
--
-- Testing DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MyFirstDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `MyFirstDB` ;

-- -----------------------------------------------------
-- Table `MyFirstDB`.`Sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyFirstDB`.`Sales` (
  `ID` INT NOT NULL,
  `Sale` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyFirstDB`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyFirstDB`.`Client` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `SummAllTime` VARCHAR(45) NOT NULL,
  `SaleID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ForeignKey_idx` (`SaleID` ASC) VISIBLE,
  CONSTRAINT `ForeignKey`
    FOREIGN KEY (`SaleID`)
    REFERENCES `MyFirstDB`.`Sales` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE SET NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `MyFirstDB`.`Sales`
-- -----------------------------------------------------
START TRANSACTION;
USE `MyFirstDB`;
INSERT INTO `MyFirstDB`.`Sales` (`ID`, `Sale`) VALUES (1, 0);
INSERT INTO `MyFirstDB`.`Sales` (`ID`, `Sale`) VALUES (2, 5);
INSERT INTO `MyFirstDB`.`Sales` (`ID`, `Sale`) VALUES (3, 10);
INSERT INTO `MyFirstDB`.`Sales` (`ID`, `Sale`) VALUES (4, 15);

COMMIT;


-- -----------------------------------------------------
-- Data for table `MyFirstDB`.`Client`
-- -----------------------------------------------------
START TRANSACTION;
USE `MyFirstDB`;
INSERT INTO `MyFirstDB`.`Client` (`ID`, `Name`, `SummAllTime`, `SaleID`) VALUES (1, 'Ляпушкин А.В.', '0', NULL);

COMMIT;

